import {
  isMachineRecord,
  Machine,
  MACHINE_CODE_PATTERN,
  normalizeMachineCode,
} from './machine.model';

describe('machine model', () => {
  const valid: Machine = { id: '1', code: 'ENV-01', name: 'Envasadora línea 1', partCount: 0 };

  const without = (field: keyof Machine) =>
    Object.fromEntries(Object.entries(valid).filter(([key]) => key !== field));

  describe('isMachineRecord', () => {
    it('accepts a well-formed record', () => {
      expect(isMachineRecord(valid)).toBe(true);
    });

    it('accepts an id generated by the server (alphanumeric)', () => {
      expect(isMachineRecord({ ...valid, id: 'o89hc_hyt6A' })).toBe(true);
    });

    it.each(['id', 'code', 'name'] as const)('rejects a record without %s', (field) => {
      expect(isMachineRecord(without(field))).toBe(false);
    });

    it.each([
      ['an empty id', { id: '' }],
      ['a blank id', { id: '  ' }],
      ['a numeric id', { id: 1 }],
      ['a null id', { id: null }],
    ])('rejects a record with %s', (_label, override) => {
      expect(isMachineRecord({ ...valid, ...override })).toBe(false);
    });

    it.each([
      ['an empty name', { name: '' }],
      ['a blank name', { name: '   ' }],
      ['a non-string name', { name: 7 }],
      ['a null name', { name: null }],
    ])('rejects a record with %s', (_label, override) => {
      expect(isMachineRecord({ ...valid, ...override })).toBe(false);
    });

    it.each([
      ['an empty code', { code: '' }],
      ['a non-string code', { code: 42 }],
      ['a null code', { code: null }],
      ['a code with spaces', { code: 'ENV 01' }],
      ['a code that starts with a hyphen', { code: '-ENV' }],
      ['a path traversal', { code: '../users' }],
      ['a code longer than 20 characters', { code: 'A'.repeat(21) }],
      ['a code that is not normalized (lowercase)', { code: 'env-01' }],
      ['a code with surrounding spaces', { code: ' ENV-01 ' }],
    ])('rejects a record with %s', (_label, override) => {
      expect(isMachineRecord({ ...valid, ...override })).toBe(false);
    });

    it.each([
      ['null', null],
      ['undefined', undefined],
      ['a string', 'ENV-01'],
      ['a number', 1],
      ['an empty object', {}],
    ])('rejects %s', (_label, value) => {
      expect(isMachineRecord(value)).toBe(false);
    });
  });

  describe('normalizeMachineCode', () => {
    it('trims and uppercases the code', () => {
      expect(normalizeMachineCode(' env-01 ')).toBe('ENV-01');
    });

    it('leaves an already normalized code unchanged', () => {
      expect(normalizeMachineCode('ENV-01')).toBe('ENV-01');
    });

    it('makes codes that differ only in case or spacing equal', () => {
      expect(normalizeMachineCode('Env-01')).toBe(normalizeMachineCode(' ENV-01\t'));
    });

    it('does not repair the format: an invalid code stays invalid after normalizing', () => {
      expect(MACHINE_CODE_PATTERN.test(normalizeMachineCode('env 01'))).toBe(false);
    });
  });

  describe('MACHINE_CODE_PATTERN', () => {
    it.each(['ENV-01', '0042', 'A', 'A-B-C', 'A'.repeat(20)])('accepts %s', (code) => {
      expect(MACHINE_CODE_PATTERN.test(code)).toBe(true);
    });

    it.each(['', '-X', 'a b', '../x', 'A'.repeat(21), 'env-01', 'ENV_01', 'ENV-01\n'])(
      'rejects %j',
      (code) => {
        expect(MACHINE_CODE_PATTERN.test(code)).toBe(false);
      },
    );
  });
});
