import { Machine } from './machine.model';
import {
  BREADCRUMB_SEPARATOR,
  buildBreadcrumb,
  buildPartTree,
  flattenPartTree,
  hasChildren,
  isPartRecord,
  Part,
  PartNode,
} from './part.model';

const part = (
  id: string,
  parentId: string | null,
  name = `Parte ${id}`,
  machineId = 'm1',
): Part => ({
  id,
  machineId,
  parentId,
  name,
});

function countNodes(nodes: readonly PartNode[]): number {
  return nodes.reduce((total, node) => total + 1 + countNodes(node.children), 0);
}

// Árbol de referencia (5 niveles):
//   1 Mesa de transporte
//   ├─ 2 Cinta 1
//   │   └─ 3 Motor de cinta
//   │       └─ 4 Rodamiento
//   │           └─ 5 Sello
//   └─ 6 Cinta 2            (hoja hermana de "Cinta 1", nivel 2)
//   7 Cabezal de sellado     (segunda raíz)
const ordered: Part[] = [
  part('1', null, 'Mesa de transporte'),
  part('2', '1', 'Cinta 1'),
  part('3', '2', 'Motor de cinta'),
  part('4', '3', 'Rodamiento'),
  part('5', '4', 'Sello'),
  part('6', '1', 'Cinta 2'),
  part('7', null, 'Cabezal de sellado'),
];

describe('part model', () => {
  describe('isPartRecord', () => {
    const valid = part('2', '1', 'Cinta 1');
    const without = (field: keyof Part) =>
      Object.fromEntries(Object.entries(valid).filter(([key]) => key !== field));

    it('accepts a child part', () => {
      expect(isPartRecord(valid)).toBe(true);
    });

    it('accepts a first-level part (parentId null)', () => {
      expect(isPartRecord(part('1', null))).toBe(true);
    });

    it('accepts ids generated by the server', () => {
      expect(isPartRecord(part('o89hc_hyt6A', 'V5mOqMqgFi8'))).toBe(true);
    });

    it.each(['id', 'machineId', 'parentId', 'name'] as const)(
      'rejects a record without %s',
      (field) => {
        expect(isPartRecord(without(field))).toBe(false);
      },
    );

    it.each([
      ['an empty id', { id: '' }],
      ['a numeric id', { id: 2 }],
      ['an empty machineId', { machineId: '' }],
      ['a blank machineId', { machineId: '  ' }],
      ['a numeric machineId', { machineId: 1 }],
      ['an empty parentId (must be null, not "")', { parentId: '' }],
      ['a numeric parentId', { parentId: 1 }],
      ['an undefined parentId', { parentId: undefined }],
      ['a parentId equal to its own id', { parentId: '2' }],
      ['an empty name', { name: '' }],
      ['a blank name', { name: '   ' }],
      ['a non-string name', { name: 7 }],
    ])('rejects a record with %s', (_label, override) => {
      expect(isPartRecord({ ...valid, ...override })).toBe(false);
    });

    it.each([
      ['null', null],
      ['undefined', undefined],
      ['a string', '2'],
      ['a number', 2],
      ['an empty object', {}],
    ])('rejects %s', (_label, value) => {
      expect(isPartRecord(value)).toBe(false);
    });
  });

  describe('buildPartTree', () => {
    it('returns empty roots and orphans when there are no parts', () => {
      expect(buildPartTree([])).toEqual({ roots: [], orphans: [] });
    });

    // Criterio 1 del spec: no se puede aplanar la jerarquía ni perder un nivel.
    it('nests every part under its parent across 5 levels', () => {
      const { roots, orphans } = buildPartTree(ordered);

      expect(orphans).toEqual([]);
      expect(roots.map((node) => node.part.name)).toEqual([
        'Mesa de transporte',
        'Cabezal de sellado',
      ]);

      const table = roots[0]!;
      expect(table.children.map((node) => node.part.name)).toEqual(['Cinta 1', 'Cinta 2']);

      const belt = table.children[0]!;
      const motor = belt.children[0]!;
      const bearing = motor.children[0]!;
      const seal = bearing.children[0]!;

      expect(motor.part.name).toBe('Motor de cinta');
      expect(bearing.part.name).toBe('Rodamiento');
      expect(seal.part.name).toBe('Sello');
      expect(seal.children).toEqual([]);
      expect(table.children[1]!.children).toEqual([]);
      expect(roots[1]!.children).toEqual([]);
    });

    it('does not flatten: only first-level parts are roots', () => {
      const { roots } = buildPartTree(ordered);

      expect(roots).toHaveLength(2);
      expect(countNodes(roots)).toBe(ordered.length);
    });

    it('builds the same hierarchy when children come before their parents', () => {
      // Orden de entrada: 5, 3, 7, 4, 6, 2, 1. Las raíces (7, 1) y los hijos de 1 (6, 2) salen
      // en el orden de entrada; lo que no puede cambiar es quién cuelga de quién.
      const shuffled = [
        ordered[4]!,
        ordered[2]!,
        ordered[6]!,
        ordered[3]!,
        ordered[5]!,
        ordered[1]!,
        ordered[0]!,
      ];

      const { roots, orphans } = buildPartTree(shuffled);

      expect(orphans).toEqual([]);
      expect(flattenPartTree(roots).map((item) => [item.part.id, item.depth])).toEqual([
        ['7', 0],
        ['1', 0],
        ['6', 1],
        ['2', 1],
        ['3', 2],
        ['4', 3],
        ['5', 4],
      ]);
    });

    it('keeps siblings in input order', () => {
      const parts = [part('1', null), part('c', '1'), part('a', '1'), part('b', '1')];

      const [root] = buildPartTree(parts).roots;

      expect(root!.children.map((node) => node.part.id)).toEqual(['c', 'a', 'b']);
    });

    it('keeps root order', () => {
      const parts = [part('b', null), part('a', null)];

      expect(buildPartTree(parts).roots.map((node) => node.part.id)).toEqual(['b', 'a']);
    });

    it('keeps the same Part objects (no copies)', () => {
      const { roots } = buildPartTree(ordered);

      expect(roots[0]!.part).toBe(ordered[0]);
    });

    it('does not mutate the input', () => {
      const input = [...ordered];
      const snapshot = structuredClone(input);

      buildPartTree(input);

      expect(input).toEqual(snapshot);
    });

    it('handles a very deep chain without overflowing the stack', () => {
      const depth = 20000;
      const chain = Array.from({ length: depth }, (_, index) =>
        part(String(index), index === 0 ? null : String(index - 1)),
      );

      const { roots, orphans } = buildPartTree(chain);
      const flat = flattenPartTree(roots);

      expect(orphans).toEqual([]);
      expect(flat).toHaveLength(depth);
      expect(flat.at(-1)!.depth).toBe(depth - 1);
    });

    describe('orphans (criterio 2: nunca se pierden en silencio)', () => {
      it('reports a part whose parent does not exist', () => {
        const lost = part('9', 'no-existe');

        const { roots, orphans } = buildPartTree([part('1', null), lost]);

        expect(orphans).toEqual([lost]);
        expect(countNodes(roots)).toBe(1);
      });

      it('reports the whole subtree left behind when a parent is missing', () => {
        // Se borró "2" a mano (JSON Server no tiene cascada): 3 y 4 quedan colgando.
        const parts = [part('1', null), part('3', '2'), part('4', '3')];

        const { roots, orphans } = buildPartTree(parts);

        expect(orphans.map((orphan) => orphan.id)).toEqual(['3', '4']);
        expect(countNodes(roots)).toBe(1);
      });

      it('reports a part whose parent belongs to another machine', () => {
        const cross = part('2', '1', 'Cruzada', 'm2');

        const { roots, orphans } = buildPartTree([part('1', null), cross]);

        expect(orphans).toEqual([cross]);
        expect(roots[0]!.children).toEqual([]);
      });

      it('reports the descendants of a cross-machine part as orphans too', () => {
        const cross = part('2', '1', 'Cruzada', 'm2');
        const below = part('3', '2', 'Debajo', 'm2');

        const { orphans } = buildPartTree([part('1', null), cross, below]);

        expect(orphans).toEqual([cross, below]);
      });

      it('terminates and reports a cycle A → B → A', () => {
        const a = part('a', 'b');
        const b = part('b', 'a');

        const { roots, orphans } = buildPartTree([part('1', null), a, b]);

        expect(orphans).toEqual([a, b]);
        expect(countNodes(roots)).toBe(1);
      });

      it('terminates and reports a part that is its own parent', () => {
        const self = part('a', 'a');

        const { roots, orphans } = buildPartTree([self]);

        expect(roots).toEqual([]);
        expect(orphans).toEqual([self]);
      });

      it('places the first of two parts with the same id and reports the repeated one', () => {
        const first = part('1', null, 'Original');
        const child = part('2', '1');
        const repeated = part('1', null, 'Repetida');

        const { roots, orphans } = buildPartTree([first, child, repeated]);

        expect(orphans).toEqual([repeated]);
        expect(roots).toHaveLength(1);
        expect(roots[0]!.part).toBe(first);
        // Los hijos no se cuelgan dos veces por el id repetido.
        expect(countNodes(roots)).toBe(2);
      });

      it('reports a repeated id found below a root', () => {
        const repeated = part('2', '1', 'Repetida');

        const { roots, orphans } = buildPartTree([
          part('1', null),
          part('2', '1', 'Original'),
          repeated,
        ]);

        expect(orphans).toEqual([repeated]);
        expect(countNodes(roots)).toBe(2);
      });

      it('never loses a part: every one ends up in the tree or in orphans', () => {
        const messy = [
          ...ordered,
          part('x', 'no-existe'),
          part('y', 'x'),
          part('c1', 'c2'),
          part('c2', 'c1'),
          part('s', 's'),
          part('1', null, 'Repetida'),
          part('z', '1', 'Cruzada', 'm2'),
        ];

        const { roots, orphans } = buildPartTree(messy);

        expect(countNodes(roots) + orphans.length).toBe(messy.length);
        expect(orphans.map((orphan) => orphan.id).sort()).toEqual(
          ['1', 'c1', 'c2', 's', 'x', 'y', 'z'].sort(),
        );
      });
    });
  });

  describe('flattenPartTree', () => {
    it('lists every part depth-first, each parent before its children, with depths 0..4', () => {
      const flat = flattenPartTree(buildPartTree(ordered).roots);

      expect(flat.map((item) => [item.part.name, item.depth])).toEqual([
        ['Mesa de transporte', 0],
        ['Cinta 1', 1],
        ['Motor de cinta', 2],
        ['Rodamiento', 3],
        ['Sello', 4],
        ['Cinta 2', 1],
        ['Cabezal de sellado', 0],
      ]);
    });

    it('returns an empty list for an empty tree', () => {
      expect(flattenPartTree([])).toEqual([]);
    });

    it('keeps the input part objects', () => {
      const flat = flattenPartTree(buildPartTree(ordered).roots);

      expect(flat[0]!.part).toBe(ordered[0]);
    });
  });

  describe('hasChildren', () => {
    it('is true for a part that another part points at', () => {
      expect(hasChildren(ordered, '1')).toBe(true);
      expect(hasChildren(ordered, '4')).toBe(true);
    });

    it('is false for a leaf', () => {
      expect(hasChildren(ordered, '5')).toBe(false);
      expect(hasChildren(ordered, '6')).toBe(false);
      expect(hasChildren(ordered, '7')).toBe(false);
    });

    it('is false for an unknown id and for an empty list', () => {
      expect(hasChildren(ordered, 'no-existe')).toBe(false);
      expect(hasChildren([], '1')).toBe(false);
    });

    it('is true even when the child belongs to another machine (better to block than orphan it)', () => {
      expect(hasChildren([part('1', null), part('2', '1', 'Cruzada', 'm2')], '1')).toBe(true);
    });
  });
});

describe('buildBreadcrumb', () => {
  const machine: Machine = { id: 'm1', code: 'ENV-01', name: 'Envasadora línea 1', partCount: 0 };

  it('is just the machine name when no part is selected', () => {
    expect(buildBreadcrumb(machine, null, ordered)).toBe('Envasadora línea 1');
    expect(buildBreadcrumb(machine, null, [])).toBe('Envasadora línea 1');
  });

  it('lists every ancestor from the machine down to a level-3 part, in order', () => {
    expect(buildBreadcrumb(machine, '3', ordered)).toBe(
      ['Envasadora línea 1', 'Mesa de transporte', 'Cinta 1', 'Motor de cinta'].join(
        BREADCRUMB_SEPARATOR,
      ),
    );
  });

  it('does not depend on the order of the input: children before their parents', () => {
    const shuffled = [...ordered].reverse();

    expect(buildBreadcrumb(machine, '5', shuffled)).toBe(
      'Envasadora línea 1 > Mesa de transporte > Cinta 1 > Motor de cinta > Rodamiento > Sello',
    );
  });

  it('is machine + first-level part for a first-level part', () => {
    expect(buildBreadcrumb(machine, '7', ordered)).toBe('Envasadora línea 1 > Cabezal de sellado');
  });

  it('gives each same-named part in a different branch its own chain', () => {
    const parts = [
      part('1', null, 'Cabezal'),
      part('2', null, 'Mordaza'),
      part('3', '1', 'Resistencia'),
      part('4', '2', 'Resistencia'),
    ];

    expect(buildBreadcrumb(machine, '3', parts)).toBe('Envasadora línea 1 > Cabezal > Resistencia');
    expect(buildBreadcrumb(machine, '4', parts)).toBe('Envasadora línea 1 > Mordaza > Resistencia');
  });

  it('uses the first occurrence when an id is repeated', () => {
    const parts = [part('1', null, 'Original'), part('1', null, 'Repetida')];

    expect(buildBreadcrumb(machine, '1', parts)).toBe('Envasadora línea 1 > Original');
  });

  it('is null when the part does not exist', () => {
    expect(buildBreadcrumb(machine, '999', ordered)).toBeNull();
    expect(buildBreadcrumb(machine, '1', [])).toBeNull();
  });

  it('is null when the part belongs to another machine', () => {
    const parts = [part('1', null, 'Cabezal', 'otra')];

    expect(buildBreadcrumb(machine, '1', parts)).toBeNull();
  });

  it('is null when an ancestor is missing, instead of a partial path', () => {
    const parts = [part('3', '2', 'Motor de cinta')];

    expect(buildBreadcrumb(machine, '3', parts)).toBeNull();
  });

  it('is null when an ancestor belongs to another machine', () => {
    const parts = [part('1', null, 'Mesa', 'otra'), part('2', '1', 'Cinta 1')];

    expect(buildBreadcrumb(machine, '2', parts)).toBeNull();
  });

  it('ends (with null) on a cycle A → B → A', () => {
    const parts = [part('a', 'b', 'A'), part('b', 'a', 'B')];

    expect(buildBreadcrumb(machine, 'a', parts)).toBeNull();
  });

  it('does not mutate the input', () => {
    const input = [...ordered];
    const snapshot = JSON.stringify(input);

    buildBreadcrumb(machine, '5', input);

    expect(JSON.stringify(input)).toBe(snapshot);
  });
});
